### ISSUE TITLE
Any instruction on how to create a basis application and build it?

### ISSUE THREAD

**Issue by darmie** [Randonee/Basis#6]
The only thing I could figure out from the Readme is how to install the Library. There is no instruction on how to create an app and build the app for the specific target.

**Comment by Randonee** [comment]
I haven't worked on this project for a while so I can't guarantee that it works with the latest haxe version.
I recommend following the build from source instructions rather than installing from haxelib. Take a look at the platform specific repos for examples.
https://github.com/Randonee/BasisAndroid
https://github.com/Randonee/BasisApple

**Comment by darmie** [comment]
Yes I saw those. And I installed them from the Repo, I was only expecting a commandline interface that creates a project and also build it. 

By the way, since what I am working on is quite similar to yours, would you be interested in building a Cross-Platform Native UI framework for Android and iOS? Something similar to https://www.nativescript.org/
